/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d9e3f6",
        "on-surface-variant": "#5a4139",
        "primary": "#a93200",
        "tertiary-fixed": "#b1f0ce",
        "tertiary-fixed-dim": "#95d4b3",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdbd0",
        "tertiary-container": "#448064",
        "surface-container": "#e6eeff",
        "secondary": "#855300",
        "on-primary-fixed": "#390b00",
        "outline": "#8e7067",
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffddb8",
        "surface-tint": "#ad3300",
        "primary-container": "#d14307",
        "on-tertiary-fixed": "#002114",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#2a1700",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#27313f",
        "tertiary": "#2a674c",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-background": "#121c2a",
        "inverse-primary": "#ffb59e",
        "outline-variant": "#e3bfb4",
        "surface-container-highest": "#d9e3f6",
        "on-primary-fixed-variant": "#842500",
        "secondary-container": "#fea619",
        "primary-fixed-dim": "#ffb59e",
        "on-secondary-fixed-variant": "#653e00",
        "surface-bright": "#f8f9ff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#684000",
        "surface": "#f8f9ff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb95f",
        "surface-container-high": "#dee9fc",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-dim": "#d0dbed",
        "on-surface": "#121c2a",
        "on-tertiary-container": "#f5fff7",
        "on-tertiary-fixed-variant": "#0e5138"
      },
      fontFamily: {
        display: ["Outfit", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        'card': '0.75rem',
        'pill': '9999px',
      },
      boxShadow: {
        'soft': '0px 4px 20px rgba(0, 0, 0, 0.05)',
        'glow': '0px 8px 30px rgba(217, 72, 15, 0.12)',
      }
    },
  },
  plugins: [],
}
